In [19]:
%config Completer.use_jedi = False

In [15]:
import numpy as np

# 넘파이 ndarray

In [6]:
array1 = np.array([1,2,3])
print(f'array1 type : {type(array1)}')
print(f'array1 shape : {array1.shape}')

array1 type : <class 'numpy.ndarray'>
array1 shape : (3,)


In [7]:
array2 = np.array([[1,2,3], [4,5,6]])
print(f'array2 type : {type(array2)}')
print(f'array2 shape : {array2.shape}')

array2 type : <class 'numpy.ndarray'>
array2 shape : (2, 3)


In [8]:
array3 = np.array([[7,8,9]])
print(f'array2 type : {type(array3)}')
print(f'array2 shape : {array3.shape}')

array2 type : <class 'numpy.ndarray'>
array2 shape : (1, 3)


In [9]:
array4 = np.array([[[10,11,12]]])
print(f'array2 type : {type(array4)}')
print(f'array2 shape : {array4.shape}')

array2 type : <class 'numpy.ndarray'>
array2 shape : (1, 1, 3)


In [10]:
print(f'array1 차원 : {array1.ndim}, array2 차원 : {array2.ndim}, array3 차원 : {array3.ndim}, array4 차원 : {array4.ndim}')

array1 차원 : 1, array2 차원 : 2, array3 차원 : 2, array4 차원 : 3


In [11]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))

<class 'list'>
<class 'numpy.ndarray'>


# ndarray의 데이터 타입
### 리스트와는 다르게 ndarray 내의 데이터 타입은 같은 데이터 타입만 가능
### 섞여 있다면 데이터 크기가 큰 타입으로 형 변환 진행
### 정수 -> 실수 : 데이터 보존, 실수 -> 정수 : 데이터 손실(소수점 이하 삭제)

In [13]:
list2 = [1, 2, "Test"]
array2 = np.array(list2)
print(array2, type(array2))

['1' '2' 'Test'] <class 'numpy.ndarray'>


In [14]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, type(array3))

[1. 2. 3.] <class 'numpy.ndarray'>


In [16]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [17]:
array_int = array_float.astype('int32')
print(array_int, array_int.dtype)

[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones

In [18]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [20]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [21]:
one_array = np.ones((3,2), dtype='int32')
print(one_array)

[[1 1]
 [1 1]
 [1 1]]


# ndarray의 차원과 크기를 변경하는 reshape()

In [22]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2,5)
print(array2)

array3 = array1.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [23]:
array4 = array1.reshape(3,4)
print(array4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [24]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print(array2)

array3 = array1.reshape(5,-1)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [26]:
array4 = array1.reshape(-1,4)
print(array4)

ValueError: cannot reshape array of size 10 into shape (4)

In [34]:
array1 = np.arange(8)
print(array1)
array3d = array1.reshape(2,2,2)
print(array3d, type(array3d))
print(array3d.tolist(), type(array3d.tolist()))

[0 1 2 3 4 5 6 7]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] <class 'numpy.ndarray'>
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]] <class 'list'>


In [33]:
# 3차원 -> 2차원 변환(-1)
array5 = array3d.reshape(-1, 1)
print(array5.tolist())
print(array5.shape)

[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


In [35]:
# 1차원 -> 2차원 변환
array6 = array1.reshape(-1, 1)
print(array6.tolist())
print(array6.shape)

[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


# ndarray의 데이터 세트 선택 - 슬라이싱

### 단일 값 추출

In [38]:
array1 = np.arange(start=1, stop=10)
print(array1)

# 3번째 값
value = array1[2]
print(value)
print(type(value))

# 맨 뒤 값
print(array1[-1])

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>
9


In [39]:
array1[0] = 9
array1[8] = 4
print(array1)

[9 2 3 4 5 6 7 8 4]


In [41]:
# axis = 0 : row(default), axis = 1 : column
array2d = np.arange(start=1, stop=10).reshape(3,3)
print(array2d)

print(array2d[0,0])
print(array2d[0,1])
print(array2d[1,0])
print(array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


### 슬라이싱

In [42]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [46]:
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [47]:
array2d = np.arange(1, 10).reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
print(array2d[0:2, 0:2])
print(array2d[1:3, 0:3])
print(array2d[1:3, :])
print(array2d[:, :])
print(array2d[:2, 1:])
print(array2d[:2, 0])

[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]


### 팬시 인덱싱

In [55]:
array2d = np.arange(1, 10).reshape(3,3)
print(array2d)

array3 = array2d[[0, 1], 2]
print(array3.tolist())

array4 = array2d[[0, 1], 0:2]
print(array4.tolist())

array5 = array2d[[0,1]]
print(array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱

In [56]:
array1d = np.arange(1, 10)
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


# 행렬의 정렬 - sort(), argsort()

### 행렬 정렬

In [57]:
org_array = np.array([3,1,9,5])
print(org_array)

# np.sort : 정렬된 새로운 배열 반환(원본 배열이 바뀌지 않는다)
sort_array1 = np.sort(org_array)
print(sort_array1)

[3 1 9 5]
[1 3 5 9]


In [58]:
# ndarray.sort : 원본 배열이 정렬
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

None
[1 3 5 9]


In [60]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [61]:
array2d = np.array([[8,12],[7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스 반환(np.argsort())

In [62]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
# 원본 행렬의 인덱스 반환
print(sort_indices)
print(type(sort_indices))

[1 0 3 2]
<class 'numpy.ndarray'>


In [64]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc) 

[2 3 0 1]


In [66]:
name_array = np.array(['junseok', 'junseok2', 'junseok3','junseok4', 'junseok5'])
score_array = np.array([78, 95, 84, 98 ,88])

sort_indices = np.argsort(score_array)
print(sort_indices)
print(name_array[sort_indices])

[0 2 4 1 3]
['junseok' 'junseok3' 'junseok5' 'junseok2' 'junseok4']


# 선형대수 연산 - 행렬 내적과 전치 행렬

### 행렬 내적(행렬 곱)

In [67]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8], [9,10], [11,12]])

dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


### 전치 행렬

In [68]:
A = np.array([[1,2], [3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
